### ISSUE TITLE
model variable defined only when using "msd" network

### ISSUE THREAD

**Issue by franzpx125** [ahendriksen/noise2inverse#1]
Hi Allard. I'm trying to replicate 03_train.ipynb but these lines:

model.save(output_dir / f"weights_epoch_{epoch}.torch", epoch)   
model.save(output_dir / "weights.torch", epoch)

work only for "msd" network. If the network is "unet" or "dncnn" the variabile "model" is not defined.

**Comment by ahendriksen** [comment]
You are entirely right! Let me fix this

**Comment by ahendriksen** [comment]
I think it's fixed with commit f638750c4e69e8cd41181bdfdd3aa3076a800604. I do not have access to a CUDA-powered machine right now. Please let me know if this works. 

Note that saving all UNet weights every epoch is a recipe for filling up your hard disk. I typically only save the weights once every 10 epochs or so.

**Comment by franzpx125** [comment]
Checked and it works for me. Now I think you need also to fix line:

model.net.eval()

in 04_evaluate.ipynb. Just removing this line for "unet" or "dncnn" worked for me. 

Thanks for the prompt fix!

**Comment by ahendriksen** [comment]
Thank you Francesco! I fixed notebook 04_evaluate.ipynb now as well :)
